/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBL;
import PBL.*;
import java.sql.*;
/**
 *
 * @author MANIAC
 */
public class student1 extends javax.swing.JFrame {
Connection conn = null;
Statement stmt =null;
    /**
     * Creates new form student1
     */
    public student1() {
        initComponents();
    }
 public void qtable()
 {
     conn=Pconnect.ConnectDB();
        try 
        {
           stmt = conn.createStatement();
           String sql ="create table q_table" +
"(id serial primary key," +
"	Question varchar(1000)," +
"	option1 varchar(500)," +
"	option2 varchar(500)," +
"	option3 varchar(500)," +
"	option4 varchar(500)," +
"	cans varchar(500));";
           stmt.executeUpdate(sql);
           stmt.close();
           conn.close();
           
        }
        catch (Exception e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);               
      }
 }
 
 public void sinfo()
 {
     conn=Pconnect.ConnectDB();
        try 
        {
           stmt = conn.createStatement();
           String sql ="create table s_info" +
"( Name1   char(50)," +
"	Div	char(1)," +
"	Roll	varchar(3));";
           stmt.executeUpdate(sql);
           stmt.close();
           conn.close();
           
        }
        catch (Exception e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);               
      }
 }
 public void login()
 {
     conn=Pconnect.ConnectDB();
        try 
        {
           stmt = conn.createStatement();
           String sql ="create table login" +
"(username varchar(50)," +
"	passwrd varchar(50));";
           stmt.executeUpdate(sql);
           stmt.close();
           conn.close();
           
        }
        catch (Exception e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);               
      }
 }
 public void insert()
 {
     conn=Pconnect.ConnectDB();
        try 
        {
           stmt = conn.createStatement();
           String sql ="insert into login(username,passwrd) values ('pbl',123)";
           stmt.executeUpdate(sql);
           stmt.close();
           conn.close();
           
        }
        catch (Exception e)
        {
            System.err.println(e.getClass().getName()+": "+e.getMessage());
            System.exit(0);               
      }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("create database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        qtable();
        sinfo();
        login();
        insert();
        System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
